language:
  - python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  # Install gccxml
  - sudo apt-get update -qq
  - sudo apt-get install -qq gccxml
  - pip install pep8

script:
  # Install pygccxml
  - python setup.py install
  # Run the tests
  - python unittests/test_all.py
