language:
  - python

python:
  - "2.7"
  - "3.3"

before_install:
  # Install gccxml
  - sudo apt-get update -qq
  - sudo apt-get install -qq gccxml

script:
  # Install pygccxml
  - python setup.py install
  # Run the tests
  - python unittests/test_all.py
